# Generated by Django 4.2.4 on 2023-08-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LEDClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('led_name', models.CharField(max_length=20)),
                ('client_id', models.CharField(max_length=20)),
                ('led_state', models.BooleanField(default=False)),
            ],
        ),
    ]
